### ISSUE TITLE
Track parents after cross over

### ISSUE THREAD

**Issue by oddoking** [kora-labs/chromax#5]
I am new to chromax, and I am very impressed by the work. When I perform cross over on a population, I think it would be very nice to track the parents of each child. So I can use this info to do decision making in a trace-back manner.

**Comment by younik** [comment]
Hello @oddoking,
Thanks for the suggestion!

I imagine you would like this feature for `random_crosses` function, correct?

**Comment by oddoking** [comment]
Thank you for considering my suggestion to improve Chromax by incorporating family information. I think this feature could significantly enhance the utility of the tool, especially in real-world genetic simulation scenarios.

I guess not just random cross but that would be a starting point.

In AlphaSimR, the ability to save an individual's father and mother's IDs allows for easy tracing along the family tree, providing valuable insights into an individual's ancestry. Implementing a similar feature in Chromax would be a valuable addition, as it would empower users to navigate complex genetic simulations effectively.

Chromax's use of a numpy-style approach, maintaining order from input to output as a matrix, offers a solid foundation. Exploring mathematical methods to enhance this functionality and better manage family-related data would be an exciting prospect for further development.

**Comment by younik** [comment]
Yes, I agree it would be helpful. However, ChromaX is designed to be _functional_ for the population (there is no population saved internally, every function requires the population as input without saving anything internal). Since individuals are an array of data and not objects (as they are in AlphaSim I believe), there is no way to assign a unique `id` to individuals.

How can this feature be designed? I believe the way is adding an output on the functions specifying the respective parent ids that produced the output population. However, for `cross`, `double_haploid`, and `diallel` this output would always be constant and straightforward to know. The only function that is "obscure" in how crosses are made is `random_crosses`, so I can add the output there, something like:

```python
>>> new_pop, parent_ids = simulator.random_crosses(pop, 200)
>>> parent_ids.shape
(200, 2)
```

Am I missing something? How do you envision this feature (maybe with a code snippet)?

**Comment by oddoking** [comment]
yes I agree with your thoughts. Population in AlphaSimR are objects and causing speed down. 

Tracking the family based on the matrix shape is straightforward as we dicussed. 

I think outputing the parent_ids of random_cross is useful and easy on your end as you do need to define the parents for the cross anyway.

**Comment by younik** [comment]
Great, I will implement this feature then, thanks for the suggestion!
